# Generated by Django 2.1.7 on 2019-12-15 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
