# Generated by Django 2.1.7 on 2019-12-15 21:25

from django.db import migrations, models
import photo_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0004_auto_20181023_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=2200, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, max_length=2200, null=True, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to=photo_blog.models.get_image_path, verbose_name='Фото'),
        ),
    ]
